name: Build and Deploy
on:
  workflow_call:
    inputs:
      regex_include:
        required: true
        type: string

      # Used to specify which path of the statik generation should remain on
      # github pages. This is used to avoid hosting books on the main website
      # hosted under unibo.it
      redirect_libri:
        required: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build resources

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cartabinaria/build-image:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Recursively compile tex files
        run: rec fconvert "\.tex$" "tectonic"

      - name: Recursively compile md files
        run: rec fconvert "\.md$" /usr/bin/md2pdf

      - name: Recursively compile (doc|ppt)x? files
        run: rec fconvert "\.(f?od(t|s|p|g))|(odf)|((doc|ppt)x?)$" "libreoffice --headless --convert-to pdf --outdir ."

      - name: Recursively compile xopp files
        run: rec fconvert "\.xopp$" /usr/bin/xopp2pdf

      - name: Recursively compile typ files
        run: rec fconvert "\.typ$" "typst compile"

      - name: Recursively compile ipynb files
        run: rec fconvert "\.ipynb$" /usr/bin/jupyter2html

      - name: Generate static directory listing
        run: >
          statik
          -page /usr/share/page.gohtml
          -style /usr/share/style.css
          -l
          -b "https://risorse.vercel.app/${{ github.event.repository.name }}/"
          -i "${{inputs.regex_include}}"
          -e "(README*|.github)"
          site

      - name: Generate site artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./site

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: "https://risorse.vercel.app/${{ github.event.repository.name }}/"

    steps:
      - name: Download static site artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
