name: Build and Deploy
on:
  workflow_call:
    inputs:
      regex_include:
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build resources

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csunibo/build-image:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      - name: Recursively compile tex files
        run: rec "\.tex$" "tectonic"
        
      - name: Recursively compile md files
        run: rec "\.md$" /usr/bin/md2pdf

      - name: Recursively compile (doc|ppt)x? files
        run: rec "\.(doc|ppt)x?$" "libreoffice --headless --convert-to pdf --outdir ."

      - name: Recursively compile xopp files
        run: rec "\.xopp$" /usr/bin/xopp2pdf

      - name: Generate static directory listing
        run: >
          statik
          -page /usr/share/page.gohtml
          -l
          -b "https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/"
          -i "${{inputs.regex_include}}"
          site

      - name: Generate site artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./site

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download static site artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: site
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
