# SPDX-FileCopyrightText: 2023 Luca Tagliavini <luca@teapot.ovh>
# SPDX-FileCopyrightText: 2024 Samuele Musiani <samu@teapot.ovh>
# SPDX-FileCopyrightText: 2024 Stefano Volpe <foxy@teapot.ovh>
#
# SPDX-License-Identifier: AGPL-3.0-only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check synta files

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cartabinaria/synta:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check the enumerazione.synta file
        run: synta check enumerazione.synta

      - name: Check the prove.synta file
        run: synta check prove.synta
